<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/public/barelytics/src/Barelytics.php';

use function Barelytics\escape;
use function Barelytics\isBot;
use function Barelytics\normalizePath;
use function Barelytics\passwordMeetsMinimum;
use function Barelytics\referrerHost;
use function Barelytics\requestCountry;
use function Barelytics\databasePath;
use function Barelytics\databaseWriteCheck;
use function Barelytics\queryColumn;
use function Barelytics\sqliteWalCheck;
use function Barelytics\runtimePrivacyChecks;

$checks = 0;
$assert = static function (bool $condition, string $message) use (&$checks): void {
    if (!$condition) { fwrite(STDERR, "FAIL: {$message}\n"); exit(1); }
    $checks++;
};

$assert(normalizePath('/articles/example') === '/articles/example', 'normal page paths are accepted');
$assert(normalizePath('/articles//example') === '/articles/example', 'repeated slashes are normalized');
$assert(normalizePath('/users/123456/profile') === '/users/:id/profile', 'numeric record identifiers are collapsed');
$assert(normalizePath('/profile/550e8400-e29b-41d4-a716-446655440000') === '/profile/:id', 'UUID-like path identifiers are collapsed');
$assert(normalizePath('/orders/01ARZ3NDEKTSV4RRFFQ69G5FAV') === '/orders/:id', 'ULID-like path identifiers are collapsed');
$assert(normalizePath('/tokens/0123456789abcdef0123456789abcdef') === '/tokens/:id', 'long hexadecimal path identifiers are collapsed');
$assert(normalizePath('/account/person@example.com') === null, 'email-like paths are rejected');
$assert(normalizePath('/account/person%40example.com') === null, 'encoded email-like paths are rejected');
$assert(normalizePath("/bad\xFFpath") === null, 'invalid UTF-8 is rejected');
$assert(normalizePath('/article?email=test@example.com') === null, 'query strings are rejected');
$assert(normalizePath('/article#fragment') === null, 'fragments are rejected');
$assert(normalizePath('https://evil.example/path') === null, 'external URLs are rejected');
$assert(normalizePath('//evil.example/path') === null, 'network-path references are rejected');
$assert(normalizePath('/' . str_repeat('a', 512)) === null, 'oversized paths are rejected');
$assert(normalizePath("/bad\0path") === null, 'control characters are rejected');
$assert(isBot('Mozilla compatible GOOGLEBOT/2.1'), 'crawler matching is case-insensitive');
$assert(isBot('MyTestRobot', ['robot']), 'custom crawler patterns are applied');
$assert(!isBot('Mozilla/5.0 (X11; Linux x86_64)'), 'ordinary browser user agents are accepted');
$assert(referrerHost('https://Example.COM/a?person=123#x') === 'example.com', 'referrer is reduced to hostname');
$assert(referrerHost('javascript:alert(1)') === null, 'non-http referrers are rejected');
$assert(referrerHost('https://user:pass@example.com/path') === null, 'userinfo referrers are rejected');
$assert(referrerHost('https://127.0.0.1/path') === null, 'IP referrer hosts are rejected');
$assert(escape('<script>alert("x")</script>') === '&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;', 'HTML output is escaped');
$assert(!passwordMeetsMinimum('short'), 'short passwords are rejected');
$assert(!passwordMeetsMinimum('éééé'), 'password length is measured in characters, not UTF-8 bytes');
$assert(passwordMeetsMinimum('long-password'), '12-character password is accepted');
$installerSource = (string) file_get_contents(dirname(__DIR__) . '/public/barelytics/install.php');
$assert((bool) preg_match('/^use function Barelytics\\\\databasePath;\s*$/m', $installerSource), 'installer imports the namespaced databasePath function');
$assert(function_exists('Barelytics\\databasePath'), 'namespaced databasePath helper is available');
$runtimeChecks = runtimePrivacyChecks();
$assert(count($runtimeChecks) === 2 && count(array_filter($runtimeChecks, static fn($check) => $check['status'] !== 'PASS')) === 0, 'runtime privacy source scan passes without matching its own URL detector');
$tokenFixture = bin2hex(random_bytes(32));
$tokenPath = sys_get_temp_dir() . '/barelytics-token-' . bin2hex(random_bytes(6));
file_put_contents($tokenPath, 'sha256:' . hash('sha256', $tokenFixture));
putenv('BARELYTICS_SETUP_TOKEN_FILE=' . $tokenPath);
$assert(\Barelytics\verifySetupToken($tokenFixture), 'setup token matches its stored one-way hash');
$assert(!\Barelytics\verifySetupToken('incorrect-token'), 'setup token hash rejects incorrect values');
unlink($tokenPath);
$ftpTokenPath = sys_get_temp_dir() . '/barelytics-ftp-token-' . bin2hex(random_bytes(6));
file_put_contents($ftpTokenPath, '<?php http_response_code(404); exit; ?>' . "\nsha256:" . hash('sha256', $tokenFixture) . "\n");
putenv('BARELYTICS_SETUP_TOKEN_FILE=' . $ftpTokenPath);
$assert(\Barelytics\verifySetupToken($tokenFixture), 'FTP-uploadable PHP token file is parsed without execution');
unlink($ftpTokenPath);
putenv('BARELYTICS_SETUP_TOKEN_FILE');
putenv('BARELYTICS_SETUP_TOKEN_FILE');
$dataPath = sys_get_temp_dir() . '/barelytics-data-' . bin2hex(random_bytes(6));
mkdir($dataPath, 0700);
$resetFixture = bin2hex(random_bytes(32));
file_put_contents($dataPath . '/reset.token', 'sha256:' . hash('sha256', $resetFixture));
putenv('BARELYTICS_DATA_DIRECTORY=' . $dataPath);
$assert(\Barelytics\verifyResetToken($resetFixture), 'FTP-installed recovery token matches its hash');
$assert(!\Barelytics\verifyResetToken('incorrect-token'), 'invalid recovery token is rejected');
unlink($dataPath . '/reset.token');
rmdir($dataPath);
putenv('BARELYTICS_DATA_DIRECTORY');
$_SERVER['HTTP_CF_IPCOUNTRY'] = 'it';
$assert(requestCountry() === 'IT', 'trusted country header is stored as uppercase country code');
$_SERVER['HTTP_CF_IPCOUNTRY'] = 'ITA';
$assert(requestCountry() === 'XX', 'invalid country codes fail closed');
unset($_SERVER['HTTP_CF_IPCOUNTRY']);
$_SERVER['SCRIPT_NAME'] = '/tools/barelytics/admin.php';
$assert(\Barelytics\requestBasePath() === '/tools/barelytics/', 'subdirectory base path is derived from the current endpoint');
unset($_SERVER['SCRIPT_NAME']);
session_save_path(sys_get_temp_dir());
session_id(bin2hex(random_bytes(16)));
session_start();
$csrf = \Barelytics\csrfToken();
$assert(\Barelytics\validCsrf($csrf), 'session-bound CSRF token verifies');
$assert(!\Barelytics\validCsrf('predictable'), 'invalid CSRF token is rejected');
$_SESSION = [];
session_destroy();

$sqliteAvailable = in_array('sqlite', PDO::getAvailableDrivers(), true);
if (!$sqliteAvailable) {
    fwrite(STDOUT, "SQLite integration checks skipped: PDO SQLite is unavailable.\n");
} else {
    $tmp = sys_get_temp_dir() . '/barelytics-test-' . bin2hex(random_bytes(6));
    mkdir($tmp, 0700);
    putenv('BARELYTICS_DATABASE_PATH=' . $tmp . '/analytics.sqlite');
    try {
        $db = \Barelytics\openDatabase();
        $assert(\Barelytics\runSelfTest($db), 'installer self-test releases all PDO statements and commits its probe');
        $crudProbe = databaseWriteCheck($db);
        $assert($crudProbe['ready'], 'installer CRUD probe creates, reads, deletes, commits, and drops its database test table');
        $assert(array_column($crudProbe['steps'], 'name') === ['CREATE TABLE', 'BEGIN', 'INSERT', 'SELECT', 'DELETE', 'COMMIT', 'DROP TABLE'], 'database probe reports each operation separately');
        $walProbe = sqliteWalCheck($db, databasePath());
        $assert($walProbe['ready'], 'installer WAL check passes when WAL sidecars are available or SQLite uses its fallback mode');
        if ($walProbe['mode'] === 'wal') $assert(is_file(databasePath() . '-wal') && is_file(databasePath() . '-shm'), 'WAL probe verifies both SQLite sidecar files');
        $failedWalProbe = sqliteWalCheck($db, $tmp . '/missing/analytics.sqlite');
        $assert(!$failedWalProbe['ready'] && $crudProbe['ready'], 'a WAL diagnostic failure does not change the independent successful CRUD result');
        $assert(\Barelytics\schemaVersion($db) === \Barelytics\CURRENT_SCHEMA_VERSION, 'fresh database receives the current schema migration');
        $assert(\Barelytics\migrateDatabase($db) === \Barelytics\CURRENT_SCHEMA_VERSION, 'schema migration is safe to repeat');
        \Barelytics\setSetting($db, 'setup_complete', '1');
        \Barelytics\setSetting($db, 'admin_password_hash', password_hash('existing-admin-password', PASSWORD_DEFAULT));
        $assert(\Barelytics\tableExists($db, 'settings') && \Barelytics\setting($db, 'setup_complete', '0') === '1' && \Barelytics\schemaVersion($db) === 2, 'schema-2 database helpers close cursors before follow-up operations');
        $existingHash = \Barelytics\setting($db, 'admin_password_hash', '');
        $existingViews = (int) \Barelytics\queryColumn($db, 'SELECT COALESCE(SUM(views), 0) FROM pageviews_daily');
        $existingProbe = databaseWriteCheck($db);
        $assert($existingProbe['ready'] && \Barelytics\schemaVersion($db) === 2, 'existing schema-2 database passes CRUD probe without migration');
        $assert(\Barelytics\setting($db, 'setup_complete', '0') === '1' && \Barelytics\setting($db, 'admin_password_hash', '') === $existingHash && (int) \Barelytics\queryColumn($db, 'SELECT COALESCE(SUM(views), 0) FROM pageviews_daily') === $existingViews, 'diagnostic probe preserves setup, admin hash, and analytics aggregates');
        $readOnlyDb = \Barelytics\connectReadOnlyDatabase();
        $readOnlyWriteBlocked = false;
        try { $readOnlyDb->exec('CREATE TABLE read_only_guard (value TEXT)'); } catch (PDOException) { $readOnlyWriteBlocked = true; }
        $assert($readOnlyWriteBlocked, 'read-only diagnostics connection cannot modify the database');
        unset($readOnlyDb);
        $privacy = \Barelytics\effectivePrivacyConfig($db);
        $assert($privacy['profile'] === 'strict' && !$privacy['country_collection'] && !$privacy['referrer_collection'] && !$privacy['browser_collection'] && !$privacy['device_collection'] && !$privacy['os_collection'], 'fresh installs use Strict Mode with every optional dimension disabled');
        $assert(\Barelytics\privacySelfTest($db)['result'] === 'PASS', 'fresh strict profile passes the runtime privacy self-test');
        $_SERVER['HTTP_USER_AGENT'] = 'Mozilla/5.0 Chrome/120.0 Windows';
        $_SERVER['HTTP_REFERER'] = 'https://private.example/search?email=secret@example.com';
        $_SERVER['HTTP_CF_IPCOUNTRY'] = 'IT';
        $assert(\Barelytics\countRequest($db, '/about'), 'strict request is counted');
        $strict = $db->query("SELECT country, views FROM pageviews_daily WHERE path = '/about'")->fetch();
        $assert($strict['country'] === 'XX' && (int) $strict['views'] === 1, 'strict request stores only the aggregate path and default country placeholder');
        $assert((int) $db->query('SELECT COUNT(*) FROM referrers_daily')->fetchColumn() === 0 && (int) $db->query('SELECT COUNT(*) FROM dimensions_daily')->fetchColumn() === 0, 'disabled dimensions are not persisted');
        $assert(!\Barelytics\countRequest($db, '/account/42'), 'default private path exclusion prevents an analytics write');
        $before = (int) $db->query('SELECT SUM(views) FROM pageviews_daily')->fetchColumn();
        $payload = ['path' => '/about', 'country' => 'IT', 'visitor_id' => 'abc', 'email' => 'person@example.com'];
        $assert(isset($payload['visitor_id']) && \Barelytics\countRequest($db, normalizePath($payload['path'])), 'server collector counts the validated path independently of client-added properties');
        $after = (int) $db->query('SELECT SUM(views) FROM pageviews_daily')->fetchColumn();
        $assert($after === $before + 1 && (int) $db->query('SELECT COUNT(*) FROM referrers_daily')->fetchColumn() === 0, 'extra client properties cannot cause collection of disabled dimensions');
        foreach (['country_collection','referrer_collection','browser_collection','device_collection','os_collection'] as $key) \Barelytics\setSetting($db, $key, '1');
        \Barelytics\recordPrivacyConfiguration($db);
        $assert(\Barelytics\effectivePrivacyConfig($db)['profile'] === 'extended', 'enabling optional dimensions computes the Extended profile');
        $assert(\Barelytics\countRequest($db, '/extended'), 'extended request is counted');
        $assert((int) $db->query("SELECT COUNT(*) FROM referrers_daily WHERE path = '/extended'")->fetchColumn() === 1, 'enabled referrer collection stores only an aggregate hostname');
        $assert((int) $db->query("SELECT COUNT(DISTINCT dimension) FROM dimensions_daily WHERE path = '/extended'")->fetchColumn() === 3, 'enabled browser, device and OS collection stores coarse aggregate categories');
        $historyCount = (int) $db->query('SELECT COUNT(*) FROM privacy_configuration_history')->fetchColumn();
        $assert($historyCount >= 2, 'material privacy configuration changes are recorded in history');
        $unknown = \Barelytics\schemaAudit($db, 'EXTENDED', \Barelytics\effectivePrivacyConfig($db));
        $assert($unknown['status'] === 'PASS', 'aggregate-only extended schema passes audit');
        $assert(\Barelytics\pathIsExcluded('/admin/users', ['/admin/*']), 'wildcard path exclusion matches nested routes');
        $rowsBeforePreparedUpserts = (int) $db->query('SELECT COUNT(*) FROM pageviews_daily')->fetchColumn();
        $hostilePath = "/x'); DROP TABLE pageviews_daily;--";
        \Barelytics\recordPageview($db, '/article', 'IT', null);
        \Barelytics\recordPageview($db, $hostilePath, 'XX', null);
        $count = (int) $db->query('SELECT COUNT(*) FROM pageviews_daily')->fetchColumn();
        $hostileRow = $db->prepare('SELECT COUNT(*) FROM pageviews_daily WHERE path = :path');
        $hostileRow->execute([':path' => $hostilePath]);
        $assert($count === $rowsBeforePreparedUpserts + 2 && (int) $hostileRow->fetchColumn() === 1, 'prepared upsert stores hostile strings as data and retains table');
        $hostileRow->closeCursor();
        $views = (int) $db->query("SELECT views FROM pageviews_daily WHERE path = '/article'")->fetchColumn();
        $assert($views === 1, 'aggregate counter increments');
        $assert(!str_contains(file_get_contents($tmp . '/analytics.sqlite') ?: '', '192.0.2.1'), 'database does not contain fixture IP');
        unset($db);
    } finally {
        foreach (glob($tmp . '/*') ?: [] as $file) @unlink($file);
        @rmdir($tmp);
        putenv('BARELYTICS_DATABASE_PATH');
    }
}

fwrite(STDOUT, "Passed {$checks} Barelytics checks.\n");
